# Generated by Django 3.1.6 on 2021-03-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_from',
            new_name='fromm',
        ),
    ]
