# Generated by Django 3.1.6 on 2021-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210316_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Такси'), (1, 'Доставка')], default=0),
        ),
    ]
