# Generated by Django 3.1.6 on 2021-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женчина')], max_length=7),
        ),
    ]
