# Generated by Django 3.1.7 on 2021-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210316_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
