# Generated by Django 3.1.7 on 2021-03-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210316_1240'),
        ('cars', '0006_auto_20210316_1204'),
    ]

    operations = [
    ]
