# Generated by Django 3.1.7 on 2021-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_type',
            field=models.IntegerField(choices=[(0, 'Қалалар арасында'), (1, 'Қала ішінде')], default=0),
        ),
    ]
