# Generated by Django 3.1.7 on 2021-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_order_city_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
